spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopicStatus: "order-status-topic"
    kafkaMessageTopicOrder: "order-topic"
    kafkaMessageGroupId: "kafka-message-group-id"

server:
  port: 8090